# Generated by Django 5.2.5 on 2025-08-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sector (e.g., Technology, Healthcare, Finance)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of the sector name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this sector encompasses')),
                ('category', models.CharField(choices=[('industry', 'Industry'), ('service', 'Service'), ('technology', 'Technology'), ('nonprofit', 'Non-Profit'), ('government', 'Government'), ('education', 'Education'), ('other', 'Other')], default='industry', help_text='High-level category for this sector', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sector is currently active and available')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this sector prominently')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for displaying sectors (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the plan (e.g., Basic, Pro, Enterprise)', max_length=100, unique=True)),
                ('plan_id', models.CharField(help_text='ID of the plan (e.g., basic, pro, enterprise)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this plan does')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently active and available')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this plan prominently')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(help_text='Sector of the plan', on_delete=django.db.models.deletion.CASCADE, to='api.sector')),
            ],
            options={
                'verbose_name': 'Plan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToolsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tool (e.g., Google Search, Wikipedia, etc.)', max_length=100, unique=True)),
                ('tool_id', models.CharField(help_text='ID of the tool (e.g., google-search, wikipedia, etc.)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this tool does')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tool is currently active and available')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this tool prominently')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(help_text='Sector of the tool', on_delete=django.db.models.deletion.CASCADE, to='api.sector')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['name'],
            },
        ),
    ]
