# Generated by Django 5.2.5 on 2025-08-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolsmodel',
            name='sector',
        ),
        migrations.AddField(
            model_name='toolsmodel',
            name='sectors',
            field=models.ManyToManyField(help_text='Sectors that can use this tool', to='api.sector'),
        ),
    ]
